//! Output formatting for gossan findings.
//!
//! Delegates to [`santh_output`] for the JSON / Jsonl / SARIF /
//! Markdown / Text renderers and renders the masscan-grepable form
//! locally so gossan can be a drop-in `masscan -oG` replacement.

use gossan_core::{OutputConfig, OutputFormat};
use secfinding::{Evidence, Finding};
use std::io::Write;

/// Print findings using the configured output format.
pub fn print_findings(findings: &[Finding], config: &OutputConfig) {
    // Masscan-grepable is rendered locally — secfinding has no
    // structured Service evidence variant, so we work with the
    // existing `Evidence::Banner` payload + finding tags.
    match config.format {
        OutputFormat::MasscanGrep => {
            let body = render_masscan_grepable(findings);
            write_to_output(body.as_bytes(), config);
            return;
        }
        OutputFormat::NmapXml => {
            let body = render_nmap_xml(findings);
            write_to_output(body.as_bytes(), config);
            return;
        }
        OutputFormat::Graphml => {
            let body = render_graphml(findings);
            write_to_output(body.as_bytes(), config);
            return;
        }
        _ => {}
    }

    let format = match config.format {
        OutputFormat::Json => santh_output::Format::Json,
        OutputFormat::Jsonl => santh_output::Format::Jsonl,
        OutputFormat::Sarif => santh_output::Format::Sarif,
        OutputFormat::Markdown => santh_output::Format::Markdown,
        OutputFormat::Text => santh_output::Format::Text,
        OutputFormat::MasscanGrep | OutputFormat::NmapXml | OutputFormat::Graphml => {
            unreachable!("handled above")
        }
    };

    let rendered = match santh_output::render(findings, format, "gossan") {
        Ok(s) => s,
        Err(e) => {
            tracing::error!("Failed to render findings: {}", e);
            return;
        }
    };

    if let Some(path) = &config.path {
        if let Ok(mut file) = std::fs::File::create(path) {
            if let Err(e) = santh_output::emit(&rendered, &mut file) {
                tracing::warn!(path = %path, "failed to write findings to output file: {e}");
            }
        } else {
            tracing::error!("Failed to open output file");
        }
    } else if let Err(e) = santh_output::emit(&rendered, std::io::stdout()) {
        tracing::warn!("failed to write findings to stdout: {e}");
    }
}

fn write_to_output(bytes: &[u8], config: &OutputConfig) {
    if let Some(path) = &config.path {
        match std::fs::File::create(path) {
            Ok(mut f) => {
                if let Err(e) = f.write_all(bytes) {
                    tracing::warn!(path = %path, err = %e, "failed to write findings to output file");
                }
            }
            Err(e) => {
                tracing::error!(path = %path, err = %e, "failed to open output file");
            }
        }
    } else {
        let _ = std::io::stdout().write_all(bytes);
    }
}

/// Render findings in the masscan grepable (`-oG`) format.
///
/// Per masscan(1):
/// ```text
/// # Masscan compatible — generated by gossan
/// Host: 1.2.3.4 ()  Ports: 80/open/tcp//http//
/// Host: 1.2.3.4 ()  Ports: 443/open/tcp//https//
/// ```
///
/// Lines are emitted only for findings whose tags include both `port:N`
/// and `ip:1.2.3.4` (gossan-portscan and gossan-engine emit those tags
/// on every open-port discovery — see the matching `add_masscan_tags`
/// helper). Non-port findings are skipped — the format has no slot
/// for them.
pub fn render_masscan_grepable(findings: &[Finding]) -> String {
    let mut out = String::new();
    out.push_str("# Masscan compatible — generated by gossan\n");
    for f in findings {
        let Some(ip) = tag_value(f, "ip:") else {
            continue;
        };
        let Some(port_proto) = tag_value(f, "port:") else {
            continue;
        };
        // `port:80/tcp` → port="80", proto="tcp"
        let (port, proto) = match port_proto.split_once('/') {
            Some((p, t)) => (p, t),
            None => (port_proto.as_str(), "tcp"),
        };
        let service = tag_value(f, "service:").unwrap_or_default();
        out.push_str(&format!(
            "Host: {ip} ()\tPorts: {port}/open/{proto}//{service}//\n"
        ));
    }
    out
}

/// First tag matching `prefix` (e.g. `port:`), with the prefix stripped.
fn tag_value(f: &Finding, prefix: &str) -> Option<String> {
    f.tags()
        .iter()
        .find(|t| t.starts_with(prefix))
        .map(|t| t[prefix.len()..].to_string())
}

/// Render findings in the nmap-XML (`-oX`) compatible shape.
///
/// Emits the subset that downstream parsers (zenmap, ndiff, etc.) rely
/// on: `<nmaprun>` root, one `<host>` per discovered IP, one `<port>`
/// child per open port. Findings without an `ip:` tag are skipped — the
/// format has no slot for non-port findings.
pub fn render_nmap_xml(findings: &[Finding]) -> String {
    use std::collections::BTreeMap;
    let mut hosts: BTreeMap<String, Vec<(String, String, String)>> = BTreeMap::new();
    for f in findings {
        let Some(ip) = tag_value(f, "ip:") else {
            continue;
        };
        let Some(port_proto) = tag_value(f, "port:") else {
            continue;
        };
        let (port, proto) = match port_proto.split_once('/') {
            Some((p, t)) => (p.to_string(), t.to_string()),
            None => (port_proto.clone(), "tcp".to_string()),
        };
        let service = tag_value(f, "service:").unwrap_or_default();
        hosts.entry(ip).or_default().push((port, proto, service));
    }
    let mut out = String::new();
    out.push_str("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
    out.push_str("<!DOCTYPE nmaprun>\n");
    out.push_str("<nmaprun scanner=\"gossan\" args=\"gossan\" version=\"1\">\n");
    for (ip, ports) in hosts {
        out.push_str(&format!(
            "  <host><address addr=\"{}\" addrtype=\"{}\"/>\n",
            xml_escape(&ip),
            if ip.contains(':') { "ipv6" } else { "ipv4" }
        ));
        out.push_str("    <ports>\n");
        for (port, proto, service) in ports {
            out.push_str(&format!(
                "      <port protocol=\"{}\" portid=\"{}\"><state state=\"open\"/>",
                xml_escape(&proto),
                xml_escape(&port)
            ));
            if !service.is_empty() {
                out.push_str(&format!("<service name=\"{}\"/>", xml_escape(&service)));
            }
            out.push_str("</port>\n");
        }
        out.push_str("    </ports>\n  </host>\n");
    }
    out.push_str("</nmaprun>\n");
    out
}

/// Render findings as GraphML.
///
/// Each finding is a `<node>` keyed by target. Findings sharing a
/// target are connected by an undirected `<edge>`. The result loads
/// directly into Gephi, Cytoscape, or yEd.
pub fn render_graphml(findings: &[Finding]) -> String {
    use std::collections::BTreeMap;
    let mut out = String::new();
    out.push_str("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
    out.push_str("<graphml xmlns=\"http://graphml.graphdrawing.org/xmlns\">\n");
    out.push_str("  <key id=\"target\"   for=\"node\" attr.name=\"target\"   attr.type=\"string\"/>\n");
    out.push_str("  <key id=\"severity\" for=\"node\" attr.name=\"severity\" attr.type=\"string\"/>\n");
    out.push_str("  <key id=\"title\"    for=\"node\" attr.name=\"title\"    attr.type=\"string\"/>\n");
    out.push_str("  <graph id=\"gossan\" edgedefault=\"undirected\">\n");
    let mut by_target: BTreeMap<String, Vec<usize>> = BTreeMap::new();
    for (i, f) in findings.iter().enumerate() {
        let nid = format!("n{i}");
        out.push_str(&format!("    <node id=\"{nid}\">\n"));
        out.push_str(&format!(
            "      <data key=\"target\">{}</data>\n",
            xml_escape(f.target())
        ));
        out.push_str(&format!(
            "      <data key=\"severity\">{}</data>\n",
            xml_escape(&f.severity().to_string())
        ));
        out.push_str(&format!(
            "      <data key=\"title\">{}</data>\n",
            xml_escape(f.title())
        ));
        out.push_str("    </node>\n");
        by_target.entry(f.target().to_string()).or_default().push(i);
    }
    let mut edge_id = 0usize;
    for (_target, group) in by_target {
        for window in group.windows(2) {
            let (a, b) = (window[0], window[1]);
            out.push_str(&format!(
                "    <edge id=\"e{edge_id}\" source=\"n{a}\" target=\"n{b}\"/>\n"
            ));
            edge_id += 1;
        }
    }
    out.push_str("  </graph>\n</graphml>\n");
    out
}

fn xml_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '&' => out.push_str("&amp;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&apos;"),
            c if (c as u32) < 0x20 && c != '\t' && c != '\n' && c != '\r' => {}
            c => out.push(c),
        }
    }
    out
}

/// Best-effort service hint from a banner. Used by portscan / engine
/// when stamping the `service:` tag on a port-discovery finding.
#[must_use]
pub fn classify_service_hint(banner: Option<&str>, port: u16) -> Option<String> {
    let b = banner.map(str::to_ascii_lowercase).unwrap_or_default();
    if b.starts_with("ssh-") || port == 22 {
        Some("ssh".into())
    } else if b.contains("http/") || matches!(port, 80 | 8080 | 8000 | 8888) {
        Some("http".into())
    } else if matches!(port, 443 | 8443) {
        Some("https".into())
    } else if b.starts_with("220 ") && (b.contains("smtp") || port == 25) {
        Some("smtp".into())
    } else if port == 21 {
        Some("ftp".into())
    } else if port == 6379 || b.contains("noauth") {
        Some("redis".into())
    } else if port == 27017 || b.contains("mongodb") {
        Some("mongodb".into())
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use secfinding::Severity;

    fn open_port_finding(ip: &str, port: u16, proto: &str, service: Option<&str>) -> Finding {
        let mut b = Finding::builder("portscan", ip, Severity::Info)
            .title(format!("open: {port}/{proto}"))
            .detail("open port")
            .tag(format!("ip:{ip}"))
            .tag(format!("port:{port}/{proto}"));
        if let Some(s) = service {
            b = b.tag(format!("service:{s}"));
        }
        b = b.evidence(Evidence::Banner {
            raw: "test".into(),
        });
        b.build().expect("test finding builds")
    }

    #[test]
    fn render_emits_one_line_per_open_port() {
        let findings = vec![
            open_port_finding("1.2.3.4", 80, "tcp", Some("http")),
            open_port_finding("1.2.3.4", 443, "tcp", Some("https")),
            open_port_finding("1.2.3.4", 22, "tcp", Some("ssh")),
        ];
        let body = render_masscan_grepable(&findings);
        assert!(body.starts_with("# Masscan compatible"));
        let lines: Vec<&str> = body.lines().filter(|l| l.starts_with("Host:")).collect();
        assert_eq!(lines.len(), 3);
        assert!(lines[0].contains("80/open/tcp//http//"));
        assert!(lines[1].contains("443/open/tcp//https//"));
        assert!(lines[2].contains("22/open/tcp//ssh//"));
    }

    #[test]
    fn render_skips_non_port_findings() {
        let f = Finding::builder("subdomain", "example.com", Severity::Info)
            .title("Subdomain discovered")
            .detail("found")
            .build()
            .unwrap();
        let body = render_masscan_grepable(&[f]);
        assert!(!body.contains("Host:"));
    }

    #[test]
    fn render_handles_missing_service_tag() {
        let f = open_port_finding("198.51.100.7", 9999, "tcp", None);
        let body = render_masscan_grepable(&[f]);
        // Empty service slot is still valid masscan output.
        assert!(body.contains("9999/open/tcp////"));
    }

    #[test]
    fn nmap_xml_groups_ports_per_host() {
        let findings = vec![
            open_port_finding("10.0.0.1", 80, "tcp", Some("http")),
            open_port_finding("10.0.0.1", 443, "tcp", Some("https")),
            open_port_finding("10.0.0.2", 22, "tcp", Some("ssh")),
        ];
        let body = render_nmap_xml(&findings);
        assert!(body.starts_with("<?xml"));
        assert!(body.contains("<nmaprun"));
        assert!(body.contains("addr=\"10.0.0.1\""));
        assert!(body.contains("addr=\"10.0.0.2\""));
        assert!(body.contains("portid=\"80\""));
        assert!(body.contains("portid=\"443\""));
        assert!(body.contains("portid=\"22\""));
        assert!(body.contains("name=\"http\""));
        assert!(body.contains("name=\"ssh\""));
        let ipv4_count = body.matches("addrtype=\"ipv4\"").count();
        assert_eq!(ipv4_count, 2, "two distinct hosts must be emitted");
    }

    #[test]
    fn nmap_xml_handles_ipv6_addrtype() {
        let f = open_port_finding("::1", 80, "tcp", Some("http"));
        let body = render_nmap_xml(&[f]);
        assert!(body.contains("addrtype=\"ipv6\""));
        assert!(body.contains("addr=\"::1\""));
    }

    #[test]
    fn nmap_xml_skips_non_port_findings() {
        let f = Finding::builder("subdomain", "example.com", Severity::Info)
            .title("Subdomain")
            .detail("found")
            .build()
            .unwrap();
        let body = render_nmap_xml(&[f]);
        assert!(!body.contains("<host>"));
        assert!(body.contains("</nmaprun>"));
    }

    #[test]
    fn graphml_emits_node_per_finding() {
        let f1 = Finding::builder("subdomain", "example.com", Severity::Info)
            .title("Discovered")
            .detail("ct")
            .build()
            .unwrap();
        let f2 = Finding::builder("hidden", "example.com", Severity::Medium)
            .title("Admin panel")
            .detail("found")
            .build()
            .unwrap();
        let f3 = Finding::builder("portscan", "10.0.0.1", Severity::Info)
            .title("open: 80/tcp")
            .detail("open")
            .build()
            .unwrap();
        let body = render_graphml(&[f1, f2, f3]);
        assert!(body.contains("<graphml"));
        assert_eq!(body.matches("<node ").count(), 3);
        // f1 + f2 share target "example.com" → 1 edge.
        assert_eq!(body.matches("<edge ").count(), 1);
        assert!(body.contains(">example.com<"));
        assert!(body.contains(">10.0.0.1<"));
        assert!(body.contains("</graphml>"));
    }

    #[test]
    fn xml_escape_handles_special_chars() {
        let evil = "<script>alert(\"x\")</script>&'";
        let escaped = xml_escape(evil);
        assert!(!escaped.contains('<'));
        assert!(!escaped.contains('>'));
        assert!(!escaped.contains('"'));
        assert!(escaped.contains("&lt;"));
        assert!(escaped.contains("&gt;"));
        assert!(escaped.contains("&amp;"));
        assert!(escaped.contains("&quot;"));
        assert!(escaped.contains("&apos;"));
    }

    #[test]
    fn classify_service_hint_basic() {
        assert_eq!(
            classify_service_hint(Some("SSH-2.0-OpenSSH_9.7"), 22),
            Some("ssh".into())
        );
        assert_eq!(classify_service_hint(None, 80), Some("http".into()));
        assert_eq!(classify_service_hint(None, 443), Some("https".into()));
        assert_eq!(classify_service_hint(None, 6379), Some("redis".into()));
        assert_eq!(classify_service_hint(None, 27017), Some("mongodb".into()));
        assert_eq!(classify_service_hint(None, 9999), None);
    }
}


/// Print a delta summary comparing current findings against a baseline.
#[cfg(feature = "checkpoint")]
pub fn print_delta_summary(delta: &gossan_checkpoint::ScanDelta) {
    use std::io::Write;
    let mut stderr = std::io::stderr();
    let _ = writeln!(stderr);
    let _ = writeln!(stderr, "  \x1b[1mΔ Delta Report\x1b[0m");
    let _ = writeln!(stderr, "  \x1b[32m+ {} new finding(s)\x1b[0m", delta.new_findings.len());
    let _ = writeln!(stderr, "  \x1b[31m- {} resolved finding(s)\x1b[0m", delta.resolved_findings.len());
    let _ = writeln!(stderr, "  \x1b[90m= {} unchanged\x1b[0m", delta.unchanged_count);
    let _ = writeln!(stderr);

    if !delta.new_findings.is_empty() {
        let _ = writeln!(stderr, "  \x1b[32;1mNew:\x1b[0m");
        for f in &delta.new_findings {
            let _ = writeln!(stderr, "    + [{}] {} — {}", f.severity(), f.target(), f.title());
        }
    }
    if !delta.resolved_findings.is_empty() {
        let _ = writeln!(stderr, "  \x1b[31;1mResolved:\x1b[0m");
        for f in &delta.resolved_findings {
            let _ = writeln!(stderr, "    - [{}] {} — {}", f.severity(), f.target(), f.title());
        }
    }
}
